# Generated by Django 4.0.5 on 2022-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'scraped',
            },
        ),
    ]
